version: "2"
services:
  voteit:
    container_name: voteit
    image: swexbe/voteit:latest
    environment: 
      - SMTP_HOST=%HOST%
      - SMTP_PORT=%PORT%
      - SMTP_SENDER=%SENDER%
      volumes: 
        - /hdd/voteit/zeo:/app/var/zeo
        - /hdd/voteit/log:/app/var/log
        - /hdd/voteit/gamma.json:/app/var/gamma.json
      ports:
        - 9010:80
      labels:
        - "traefik.enable=true"
        - "traefik.port=80"
        - "traefik.frontend.rule=Host:voteit.swex.be"
      networks:
        - web
  networks:
    web:
      external:
        name: web